[package]
name = "flipper"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "flipper"
path = "src/main.rs"

[dependencies]
pvm = { path = "../../pvm" }
parity-scale-codec = { version = "3.6", default-features = false, features = ["derive"] }
polkavm-derive = { workspace = true }
